### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by TonSchinkel** [mannymerino/bci-calendar#1]
Great visual, but I miss some stuff. I can't choose on which day the week starts. In Holland the week starts on a Monday, not a Sunday... I also miss the option for showing the weeknumber...

**Comment by mannymerino** [comment]
Thanks for the feedback @TonSchinkel! These are both great suggestions and, in fact, setting the first weekday is a feature I was targeting for the next update.

**Comment by mannymerino** [comment]
@TonSchinkel - Both of these suggestions have been implemented. I plan on submitted a new version of the visual to the Office Store some time this week and it can take several days to appear in the store so be on the look out! I will be closing this issue as it is code complete. Thanks!
