### ISSUE TITLE
Wrong week number

### ISSUE THREAD

**Issue by sablastik** [mannymerino/bci-calendar#13]
hi. i've got duplicated week numbers like this:
![image](https://user-images.githubusercontent.com/16276988/31321270-d80619a0-ac8b-11e7-9dc2-a000ff4aab9e.png)

it happens when i change Calendar Format-> Week Start Day from sunday to any other day of week

**Comment by mannymerino** [comment]
You may need to toggle the `Use ISO week-numbering` setting to `On`. Please let me know if this resolves the issue. Thanks!

**Comment by sablastik** [comment]
Yep, that solves the problem with weeknum in calendar but now i have difference in 1 week with DAX weeknum used in other visualization
