### ISSUE TITLE
Does not work as a dashboard tile

### ISSUE THREAD

**Issue by Rumsas** [mannymerino/bci-calendar#16]
First of all thank you for this visual. It's the best calendar out there!
I am experiencing an issue when it's pinned as a dashboard tile. 
After a random period of time (less than 1hour) the contents of the calendar in the dashboard disappear.
We are having this dashboard displayed on a screen in our office and it's important that it stays visible at all times. I have tried loading data both ways - in DirectQuery and Import mode, in both instances the bug remains. Could you help, please?

**Comment by mannymerino** [comment]
Hi @Rumsas - thanks for using my calendar visual and providing the feedback! 👍 

Can you tell me a little more about your setup? Is the data used in the dashboard static, or does it refresh after some period of time? If it gets refreshed periodically, does that correlate to when the contents of the calendar disappear? Do any of the other visuals / tiles on the dashboard experience this, or is it just the calendar? Are there any other custom visuals pinned as tiles on the dashboard or are all the rest standard Power BI visuals?

I am going to test on my end, but any additional details you could provide would be helpful, including a screenshot if possible (before the issue occurs and after would be ideal).

**Comment by Rumsas** [comment]
Hi @mannymerino - thank you for such a promt response. Please see more information about my setup below.

Is the data used in the dashboard static, or does it refresh after some period of time?
Dashboard is build from various reports, using various types of connections:
Direct query to sql server; 
Daily import from sql server, 
Excel files from sharepoint;
Your calendar is coming from Direct query report.

Direct query tiles should be automatically refreshed every 15 min or so. There seems to be correlation between tile refresh and dissapearance of calendar, but not in 100% of cases. I have tried your calendar with imported data instead of direct query and it also blanked out randomly.

It's only the calendar that suffers this type of bug and yes, it's the only custom visual from the dashboard.

If you want to really test it I suggest you leave your calendar running on a dashboard overnight.

I really hope we can solve this.

Before:
![image](https://user-images.githubusercontent.com/26630035/32558617-7a29fd10-c4a5-11e7-8a50-accbcd7ba6cc.png)
After:
![image](https://user-images.githubusercontent.com/26630035/32558594-6c7ab15a-c4a5-11e7-8531-6dd0a9ba095c.png)

**Comment by mannymerino** [comment]
Thank you for the additional detail. Very helpful! I do have one additional question / request:

Would it be possible to add one other custom visual as a pinned tile to your dashboard? This way you could monitor its behavior to see if its content also disappears when the calendar content disappears. Ideally it would be connected to the same data as the calendar. I would like to root out whether or not this is a bigger issue with custom visuals, or something specific with my implementation, as that will greatly help me direct my effort.

I understand that you may not be able to allocate the time and effort for this request, so please let me know if that's the case.

**Comment by Rumsas** [comment]
Sure, I will test it within next 24 hours and will get back to you.

**Comment by Rumsas** [comment]
It's official. All custom visuals break together. I will contact Microsoft support

**Comment by mannymerino** [comment]
Thank you for the update. It's unfortunate as it doesn't solve your problem. Hopefully MS support can provide some form of a solution in a timely fashion.

I don't know which channel might get a quicker response, the support team you plan on reaching out to, or creating a new issue on the `PowerBI-visuals` GitHub page, but it might be worth posting this there as well: https://github.com/Microsoft/PowerBI-visuals/issues.

I'm going to close this issue, but feel free to respond back here if you get any updates from MS as I am curious to track this.
