### ISSUE TITLE
Data Colors: add option to force fixed colors

### ISSUE THREAD

**Issue by mannymerino** [mannymerino/bci-calendar#19]
Add an option to have the data colors selected be fixed and not scaled linearly from min to max with the logic of `If [Measure Data Field] < [Data Color Cuttoff Value] Then [Color1] Else [Color2]`

**Comment by keymillog** [comment]
any eta on this?

**Comment by mannymerino** [comment]
Hi @keymillog- I have gotten myself back into a place where I can dedicate chunks of time each week to work on the calendar visual which should hopefully translate into more frequent updates. 😃 
This request specifically is second in line on my priority list so I am expecting to get started working on it in the next week or so, and therefore would hopefully have an updated version available in AppSource in 2-3 weeks (some of that time is dependent on how long it takes MS to push the update out to the store).

**Comment by keymillog** [comment]
Any update on this? The visual fits our needs, but diverging colors are a real p.i.t.a. for us. My management keeps asking me about it every week.

**Comment by mannymerino** [comment]
@keymillog Data colors have been updated to now include an option for fixed colors! This has been submitted to MS for inclusion in the store (AppSource), but due to the fact that it is now a certified custom visual, there are extra steps involved with getting updates approved. This process was started a couple weeks ago and it has now passed all reviews and has been approved to be published, but it hasn't yet propagated into the store. I imagine this could be as soon as today (still not as recent as 06:30 PST today) or hopefully within the next couple days. The new version is 1.2.0.0 if you're keeping an eye on [AppSource](https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA104381096?tab=Overview).  In the meantime, please review the updated [README](https://github.com/mannymerino/bci-calendar#fixed-colors) that outlines the new fixed color options. 

Once it's updated in the store and you are using it, I would also love to hear if it's fitting your needs or not, and if not, what your use cases are so I can better understand your specific requirements.

**Comment by keymillog** [comment]
Hello again.

It seems that Microsoft finally  allows to update your visual since it says Version 1.2.0.0 and updated 5/14/2018.
Unfortunately the update doesn’t resolve the issue – there is no Data colors – type selection. Basically it looks like the older version.

I tried updating it from marketplace, from file downloaded on AppSource, I saved and closed the report after updating, I even downloaded the visual to a new report file and checked here – still no “type” option.

Could you look at this?

**Comment by mannymerino** [comment]
@keymillog I am seeing the same as you describe. I believe it's just a matter of getting fully propagated out to the marketplace and it's my understanding that the visual should automatically updated. But I've submitted an email to the Power BI support team regardless to see if there are any additional actions that need to be taken in order to get the visual updated in your report(s). I'll keep you posted with any additional information I receive.

**Comment by keymillog** [comment]
Hello again!
New version is now available and the addition of fixed colors is working as intented. Thanks a lot for your work and staying in touch!

**Comment by mannymerino** [comment]
@keymillog Excellent! Glad to hear it's fitting your needs. 👍
