### ISSUE TITLE
Tooltip field - "No Data" on hover

### ISSUE THREAD

**Issue by chvalean** [mannymerino/bci-calendar#30]
I'm using this plugin and seeing that although I put different columns in the Tooltip section in powerbi, when I hover over any date in the table, this gets reported as "No Data", so the tooltip is not working properly?
Thank you!

**Comment by mannymerino** [comment]
@chvalean Can you confirm 1) that you have a data field specified in the Measure Data field well; 2) the data field you are using in the Measure Data is numeric; 3) the data field you are using in the Measure Data _has data_ for the day(s) you are hovering? If these conditions are met, tooltips should be displaying as expected (see example screenshot below). Could you possibly send a screenshot along with a little more detail about how you have the calendar visual configured? Thanks!
![image](https://user-images.githubusercontent.com/13630322/42172752-c3f841fa-7dd1-11e8-9950-59fea95ac1ea.png)
_Figure 1: Tooltips in action_

**Comment by meg5** [comment]
I am also experiencing this problem but only one of my calendar days is showing the tool tip and is clickable. The other days are showing the correct colors based on the numeric data but they are not clickable (dont filter any other items in the page) and also show "No Data" message when hovering.
